### ISSUE TITLE
Unable to download checkpoint files

### ISSUE THREAD

**Issue by VigneshSrinivasan10** [xuanqing94/BayesianDefense#1]
Hi, 

The downloading of checkpoint files from `http://muradin.cs.ucdavis.edu:9876/` was not successful. I also tried to download it on chrome/firefox and also from terminal using `wget`. 

Please let me know how I can get these checkpoints :) 

Thanks,

**Comment by xuanqing94** [comment]
Sorry about that, I ran a python http server in my lab machine, which can be unstable. I will upload the checkpoints to google drive.

Right now, I just restart the http server process and it should work temporarily (although I don't expect it to work for a long time).

**Comment by VigneshSrinivasan10** [comment]
Hi @xuanqing94, 

I am sorry to say that it still does not work. 
I would like to compare my defense method with your interesting work. It would be great if you could make the checkpoints available. 

Thanks,

**Comment by xuanqing94** [comment]
@VigneshSrinivasan10 That's weird because I can open the link. Anyway please check the readme to see the google drive link, hope this will work for you.

**Comment by VigneshSrinivasan10** [comment]
@xuanqing94, it works now.. thanks a lot!
