### ISSUE TITLE
Correct use of noise_fn

### ISSUE THREAD

**Issue by zimmerrol** [xuanqing94/BayesianDefense#3]
I have a question regarding your `weight_noise.py` file. I feel that the `noise_fn` function is not really used in any other module. Let's take a look for example at the `linear.py`. Here, there are two definitions of the ` forward()` function. The first one (defined in [line 39](https://github.com/xuanqing94/BayesianDefense/blob/master/models/layers/linear.py#L39)) uses the function. But this is later overwritten in [line 46](https://github.com/xuanqing94/BayesianDefense/blob/master/models/layers/linear.py#L46) by an implementation of `forward` that does not call `noise_fn` at all. So now I have two questions: Is this really intended? Is the `noise_fn` necessary at all?

Edit: Is it correct that the `noise_fn` function is relevant if one wants to use `Bayes by Backprop` to train the network and otherwise the reparametrization trick is used?

Thanks for your help and thanks for sharing your code/experiments of your paper!

**Comment by xuanqing94** [comment]
Hi @FlashTek 
The `forward_()` function is obsolete and only `forward()` is used, if you check for example `vgg_vi.py`, you will see the `forward` function only calls `forward()` of its submodules. 
The reason I have `forward_()` here is that sometimes we don't care about KL value (at testing time),
so in this case you can call `forward_()` to make it run slightly faster.

**Comment by zimmerrol** [comment]
Ah, alright, thanks for the clarification!
