### ISSUE TITLE
Incorrect PGD implementation

### ISSUE THREAD

**Issue by ybj14** [xuanqing94/BayesianDefense#8]
https://github.com/xuanqing94/BayesianDefense/blob/master/attacker/pgd.py#L25

Here  `diff.clamp_(-eps, eps)` should be `diff = diff / diff.max() * eps`.

I wonder whether this affects the credibility of the proposed defense.

**Comment by xuanqing94** [comment]
> https://github.com/xuanqing94/BayesianDefense/blob/master/attacker/pgd.py#L25
> 
> Here `diff.clamp_(-eps, eps)` should be `diff = diff / diff.max() * eps`.
> 
> I wonder whether this affects the credibility of the proposed defense.

https://github.com/MadryLab/mnist_challenge/blob/master/pgd_attack.py#L58

**Comment by ybj14** [comment]
> > https://github.com/xuanqing94/BayesianDefense/blob/master/attacker/pgd.py#L25
> > Here `diff.clamp_(-eps, eps)` should be `diff = diff / diff.max() * eps`.
> > I wonder whether this affects the credibility of the proposed defense.
> 
> https://github.com/MadryLab/mnist_challenge/blob/master/pgd_attack.py#L58

Madry's implementation is `The attack performs k steps of
       size a` then clipped by `eps`(https://github.com/MadryLab/mnist_challenge/blob/master/pgd_attack.py#L16), while this implementation does not accept step size parameter `a`.  Use the scale of the gradient as step size is problematic as only the direction of the gradient is important.

**Comment by ybj14** [comment]
> > > https://github.com/xuanqing94/BayesianDefense/blob/master/attacker/pgd.py#L25
> > > Here `diff.clamp_(-eps, eps)` should be `diff = diff / diff.max() * eps`.
> > > I wonder whether this affects the credibility of the proposed defense.
> > 
> > 
> > https://github.com/MadryLab/mnist_challenge/blob/master/pgd_attack.py#L58
> 
> Madry's implementation is `The attack performs k steps of size a` then clipped by `eps`(https://github.com/MadryLab/mnist_challenge/blob/master/pgd_attack.py#L16), while this implementation does not accept step size parameter `a`. Use the scale of the gradient as step size is problematic as only the direction of the gradient is important.

Actually when i use this code i found attack using different `eps` given the same `adv_x`: Scale of the gradient is small enough that the clipping of `eps` never works.

**Comment by xuanqing94** [comment]
"While this impl does not accept step size":
Please see https://github.com/xuanqing94/BayesianDefense/blob/master/attacker/pgd.py#L16
Step size is a fixed value. If you feel like it is too small or too big, you can change it manually.
